image: amazonlinux:2023

stages:
  - build
  - deploy_destroy:dev

variables:
  DOMAIN_NAME:
    value: "zaproject.com"
    description: "Domain name for the WaterEye application"

include:
  - local: '.gitlab/build__script.yml'
  - local: '.gitlab/deploy_destroy__before_script.yml'
  - local: '.gitlab/deploy__script.yml'
  - local: '.gitlab/destroy__script.yml'

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build the application:
  stage: build
  script:
    - !reference [.build__script, script]
  artifacts:
    paths:
      - ./watereye

deploy to dev:
  stage: deploy_destroy:dev
  environment:
    name: dev
    url: http://${CI_PROJECT_NAME}-${CI_ENVIRONMENT_NAME}.${DOMAIN_NAME}
  needs:
    - build the application
  before_script:
    - !reference [.deploy_destroy__before_script, script]
  script:
    - !reference [.deploy__script, script]

destroy dev:
  stage: deploy_destroy:dev
  environment:
    name: dev
    action: stop
  when: manual
  needs:
    - build the application
  before_script:
    - !reference [.deploy_destroy__before_script, script]
  script:
    - !reference [.destroy__script, script]
