name: build
on: 
  push:
  workflow_dispatch:
env:
  ENV_NAME: "staging"    # var
  TIMEOUT: 30            # var

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print env
        run: echo "Deploying to $ENV_NAME with timeout $TIMEOUT seconds"
