name: demo
on: 
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "repo Var: ${{ vars.REPO_VAR }}"
          echo "repo Secret: ${{ secrets.REPO_SECRET }}"

  my_job:
    runs-on: ubuntu-latest
    environment: my_env
    steps:
      - run: |
          echo "env Var: ${{ vars.ENV_VAR }}"
          echo "repo Var: ${{ vars.REPO_VAR }}"
          echo "env Secret: ${{ secrets.ENV_SECRET }}"
          echo "repo Secret: ${{ secrets.REPO_SECRET }}"
