name: demo
on: 
  push:
  workflow_dispatch:
env:
  ENV_NAME: "staging"    # var
  TIMEOUT: 30            # var

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "env Var: ${{ vars.ENV_VAR }}"
          echo "repo Var: ${{ vars.REPO_VAR }}"
          echo "env Secret: ${{ secrets.ENV_SECRET }}"
          echo "repo Secret: ${{ secrets.REPO_SECRET }}"


  my_job:
    runs-on: ubuntu-latest
    environment: my_env
    steps:
      - run: |
          echo "env Var: ${{ vars.ENV_VAR }}"
          echo "repo Var: ${{ vars.REPO_VAR }}"
          echo "env Secret: ${{ secrets.ENV_SECRET }}"
          echo "repo Secret: ${{ secrets.REPO_SECRET }}"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print env
        run: echo "Deploying to $ENV_NAME with timeout $TIMEOUT seconds"
