name: demo
on: 
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Var: ${{ vars.MY_VAR }}"
          echo "Secret: ${{ secrets.MY_SECRET }}"
