name: demo
on: 
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MY_VAR: ${{ vars.MY_VAR }}
      MY_SECRET: ${{ secrets.MY_SECRET }}
    steps:
      - run: |
          echo "Var: ${{ vars.MY_VAR }}"
          echo "Secret: ${{ secrets.MY_SECRET }}"
